### ISSUE TITLE
Improve units of slider

### ISSUE THREAD

**Issue by cmaes** [EmilienDupont/FCNFexample#2]
Could you improve the units/steps in the slider on this page too? just like you did for fixed charge network flow?  I'm also wondering if the slider should control the fixed cost to lay wire (not the variable cost). So when wire is very cheap (and the slider is low) you see lots of flow from windmills to the sink. When wire is expensive to lay you get the nice tree structure where windmills connect to other windmills before they go to the sink. Whatever you do though, I think the default slider value should show the tree. Since this is the most intuitive solution (at least for me).

**Comment by EmilienDupont** [comment]
Slider now varies the fixed cost of laying wire. Units are in dollars per metre as explained in description. The default value fives the tree solution. I researched the cost of laying underwater cables, but it is hard to find a very good figure... So I just went with the most common values I could find (around 1k$/metre)
